---
# this is only here to let the CI tests know
# that this scenario is using docker
docker: True

# ---
# should already be in the container image
#ceph_stable: True
#ceph_origin: 'upstream' # or 'distro' or 'local'
#ceph_stable_key: https://download.ceph.com/keys/release.asc
#ceph_stable_release: jewel # ceph stable release
#ceph_stable_repo: "http://download.ceph.com/rpm-{{ ceph_stable_release }}"
# ---

ceph_docker_image_tag: tag-build-master-jewel-centos-7
mon_containerized_deployment: True
osd_containerized_deployment: True
#mds_containerized_deployment: True
#rgw_containerized_deployment: True
#cluster: test
cluster: ceph
#ceph_mon_docker_interface: eth1
ceph_mon_docker_interface: eth0

ceph_mon_docker_subnet: "{{ public_network }}"
journal_size: 100
ceph_docker_on_openstack: False

public_network: 192.168.24.0/24
cluster_network: "{{ public_network }}"

journal_collocation: true
ceph_rgw_civetweb_port: 8080
ceph_osd_docker_devices: "{{ devices }}"

devices:
   - /dev/vdb
   - /dev/vdc

# ---------------------------------------------
# ceph_conf_overrides:
#   global:
#     pool_default_pg_num: 128
#     pool_default_pgp_num: 128
#     pool_default_size: 1
#     pool_default_min_size: 1
  
# ---------------------------------------------
# MONS (won't work under containerization)

# fsid: b007365e-cc87-11e5-a877-525400330ee0
# monitor_secret: AQBtcrVWAAAAABAA4JprB4BR5klHr3mgtqmX0w==

# openstack_config: true
# openstack_glance_pool:
#   name: images
#   pg_num: "{{ osd_pool_default_pg_num }}"
# openstack_cinder_pool:
#   name: volumes
#   pg_num: "{{ osd_pool_default_pg_num }}"
# openstack_nova_pool:
#   name: vms
#   pg_num: "{{ osd_pool_default_pg_num }}"
# openstack_cinder_backup_pool:
#   name: backups
#   pg_num: "{{ osd_pool_default_pg_num }}"
# openstack_metrics_pool:
#   name: metrics
#   pg_num: "{{ osd_pool_default_pg_num }}"
  
# openstack_pools:
#   - "{{ openstack_glance_pool }}"
#   - "{{ openstack_cinder_pool }}"
#   - "{{ openstack_nova_pool }}"
#   - "{{ openstack_cinder_backup_pool }}"
#   - "{{ openstack_metrics_pool }}"  

# openstack_keys:
# - { name: client.openstack, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_pool }}, allow rwx pool={{ openstack_cinder_backup_pool }}, allow rwx pool={{ openstack_nova_pool }}, allow rwx pool={{ openstack_glance_pool }}, allow rwx pool={{ openstack_metrics_pool }}'" }
